In [1]:
import pandas as pd

In [29]:
df1=pd.DataFrame([[1,'abc','pune'],[2,'pqr','pune'],[3,'def','pune'],[8,'xyz','malkapur']],columns=['rollno','names','address'])

In [30]:
df1

   rollno names   address
0       1   abc      pune
1       2   pqr      pune
2       3   def      pune
3       8   xyz  malkapur

In [38]:
df1=pd.DataFrame([[1,'Guru','Budhvar Pet'],[2,'Aditay','Pub'],[3,'Aniket','Shrushti Hostel'],[8,'Shravan','Baner']],columns=['rollno','name','address'])

In [39]:
df1

   rollno     name          address
0       1     Guru      Budhvar Pet
1       2   Aditay              Pub
2       3   Aniket  Shrushti Hostel
3       8  Shravan            Baner

In [33]:
df2=pd.DataFrame([[1,48,68], [2,00, 60], [3,90,58], [9,44,68]],columns=['rollno','Phy','Chem'])
df2

   rollno  Phy  Chem
0       1   48    68
1       2    0    60
2       3   90    58
3       9   44    68

In [34]:
df1.set_index('rollno', inplace=True)

In [35]:
df2.set_index('rollno', inplace=True)

In [40]:
df1

   rollno     name          address
0       1     Guru      Budhvar Pet
1       2   Aditay              Pub
2       3   Aniket  Shrushti Hostel
3       8  Shravan            Baner

In [37]:
df2

        Phy  Chem
rollno
1        48    68
2         0    60
3        90    58
9        44    68